FROM nginx:1.27-alpine
RUN apk add --no-cache ca-certificates tzdata \
  && rm -f /etc/nginx/conf.d/default.conf
WORKDIR /app
COPY bin/gateway /app/gateway
ENV TZ=Asia/Shanghai
EXPOSE 8090
CMD ["/app/gateway"]
