import http from './http'

export const register = (data) => http.post('/auth/register', data)
export const login = (data) => http.post('/auth/login', data)
export const getCaptcha = () => http.get('/captcha')
export const me = () => http.get('/me')
export const listStations = (q) => http.get('/stations', { params: { q } })
export const queryTickets = (params) => http.get('/tickets', { params })
export const queryTransfers = (params) => http.get('/transfers', { params })
export const listPassengers = () => http.get('/passengers')
export const addPassenger = (data) => http.post('/passengers', data)
export const deletePassenger = (id) => http.delete(`/passengers/${id}`)
export const createOrder = (data) => http.post('/orders', data)
export const createTransferOrders = (data) => http.post('/orders/transfer', data)
export const listOrders = () => http.get('/orders')
export const getOrder = (id) => http.get(`/orders/${id}`)
export const payOrder = (id) => http.post(`/orders/${id}/pay`)
export const cancelOrder = (id) => http.post(`/orders/${id}/cancel`)
export const refundOrder = (id) => http.post(`/orders/${id}/refund`)
export const rescheduleOrder = (id, data) => http.post(`/orders/${id}/reschedule`, data)
export const createWaitlist = (data) => http.post('/waitlist', data)
export const listWaitlist = () => http.get('/waitlist')
export const cancelWaitlist = (id) => http.post(`/waitlist/${id}/cancel`)

export const adminListTrains = () => http.get('/admin/trains')
export const adminListSeats = (trainId) => http.get('/admin/seats', { params: { train_id: trainId } })
export const adminBlockSeat = (id, data) => http.post(`/admin/seats/${id}/block`, data)
export const adminUnblockSeat = (id) => http.post(`/admin/seats/${id}/unblock`)
export const adminListDayBlocks = (params) => http.get('/admin/day-blocks', { params })
export const adminUpsertDayBlock = (data) => http.post('/admin/day-blocks', data)
export const adminDeleteDayBlock = (id) => http.delete(`/admin/day-blocks/${id}`)
export const adminRebuildProjection = (data) => http.post('/admin/projections/rebuild', data)
export const adminListQuotas = () => http.get('/admin/quotas')
export const adminUpsertQuota = (data) => http.post('/admin/quotas', data)
export const adminDeleteQuota = (id) => http.delete(`/admin/quotas/${id}`)
export const adminListSalePolicies = () => http.get('/admin/sale-policies')
export const adminUpsertSalePolicy = (data) => http.post('/admin/sale-policies', data)
export const adminListSaleWaves = () => http.get('/admin/sale-waves')
export const adminUpsertSaleWave = (data) => http.post('/admin/sale-waves', data)
export const adminDeleteSaleWave = (id) => http.delete(`/admin/sale-waves/${id}`)
export const adminListRiskBlocks = () => http.get('/admin/risk-blocks')
export const adminUpsertRiskBlock = (data) => http.post('/admin/risk-blocks', data)
export const adminDeleteRiskBlock = (id) => http.delete(`/admin/risk-blocks/${id}`)

export const lookupTicket = (ticketNo) => http.get('/verify/ticket', { params: { ticket_no: ticketNo } })
export const verifyTicket = (data) => http.post('/verify/ticket', data)
export const gatewayStats = () => http.get('/gateway/stats')
